export enum apiRoutes {
  LOGIN = '/auth/login',
  FIREBASE_LOGIN = '/auth/firebaseLogin',
  REGISTER = '/auth/register',
  SIGNOUT = '/auth/signout',
  FIREBASE_SIGNOUT = '/auth/firebaseSignout',
  ME = '/users/me',
  REFRESH_TOKENS = '/auth/refresh',
  FETCH_USERS = '/users',
  USERS_PREFIX = '/users',
  PASSWORD_RESET = '/users/me/reset-password',
  UPLOAD_AVATAR_IMAGE = '/users/upload',
  FETCH_EVENTS = '/events',
  EVENTS_PREFIX = '/events',
  UPCOMING_EVENTS = '/events/upcomingEvents',
  RECENT_EVENTS = '/events/recentEvents',
  CURR_USER_CREATED_EVENTS = '/events/user/createdEvents',
  CURR_USER_UPCOMING_EVENTS = '/events/user/upcomingEvents',
  CURR_USER_RECENT_EVENTS = '/events/user/recentEvents',
  UPLOAD_EVENT_IMAGE = '/events/upload',
  FETCH_ROLES = '/roles',
  ROLES_PREFIX = '/roles',
}
